version: '3.8'
services:
  app:
    # build: .
    image: ghcr.io/vuetorrent/vuetorrent-backend:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - "./data:/app/data"
      - "./.env:/app/.env"
