services:
  app:
    build: .
#    image: ghcr.io/vuetorrent/vuetorrent-backend:latest
    restart: unless-stopped
    environment:
      - CONFIG_PATH=/config
      - PORT=3000
      - QBIT_BASE=http://host.docker.internal:8080
      # Only enable if using self-signed certificates
      # - USE_INSECURE_SSL=true
    # host.docker.internal isn't available on Linux so we must include it manually
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3000:3000"
    volumes:
      - "./data/config:/config"
